#!/usr/bin/env node
/**
 * The `secrets.env` format: writer and reader, kept together.
 *
 * The file has two consumers with different needs. A shell sources it, so it
 * must be valid POSIX with every value quoted. The resolver reads it back, so
 * the quoting must be exactly reversible. Those two requirements only stay
 * consistent if the pair lives in one module — a writer and a parser that drift
 * apart corrupt any value containing a quote, and do it silently.
 * @module envfile
 */

export { materializedOwnersMatch } from "../../lisa-setup-remote-env/assets/materialized-env-authority.mjs";

/**
 * POSIX single-quote a value so a shell reproduces it byte for byte.
 *
 * Single quotes suppress every expansion, so the only character needing care is
 * the quote itself: close the string, emit an escaped quote, reopen.
 * @param {string} value Raw value.
 * @returns {string} A single-quoted shell token.
 */
export function quote(value) {
  return `'${String(value).replaceAll("'", `'\\''`)}'`;
}

/**
 * Render selected secrets as a sourceable environment file.
 * @param {Map<string, {value: string}>} selected Secrets by exact name.
 * @returns {string} File contents, newline-terminated.
 */
export function renderEnv(selected) {
  const lines = [
    "# Generated by lisa-secrets-access. Contains secret values.",
    "# Do not print, inspect, summarize, commit, or copy this file.",
  ];
  for (const key of [...selected.keys()].sort()) {
    lines.push(`export ${key}=${quote(selected.get(key).value)}`);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Parse a file produced by {@link renderEnv} back into values.
 *
 * Deliberately strict: it understands only the shape this module writes. A line
 * it does not recognise is skipped rather than guessed at, because a partial
 * parse that yields a truncated secret is worse than one that yields nothing.
 * @param {string} text File contents.
 * @returns {Map<string, string>} Values by exact name.
 */
export function parseEnv(text) {
  const out = new Map();
  for (const line of text.split("\n")) {
    const match = /^export ([A-Za-z_][A-Za-z0-9_]*)='(.*)'$/.exec(line);
    if (!match) continue;
    out.set(match[1], match[2].replaceAll(`'\\''`, "'"));
  }
  return out;
}

/**
 * Render usage notes with every value intentionally omitted.
 *
 * The separation is the point: an agent reading a note must have no path to a
 * value, so the note file is a different file with a different reader.
 * @param {Map<string, {note: string}>} selected Secrets by exact name.
 * @returns {string} JSON contents, newline-terminated.
 */
export function renderNotes(selected) {
  const secrets = {};
  for (const key of [...selected.keys()].sort()) {
    const note = selected.get(key).note ?? "";
    if (typeof note !== "string") {
      throw new Error(`secret note is not a string: ${key}`);
    }
    secrets[key] = note;
  }
  return `${JSON.stringify({ schemaVersion: 1, secrets }, null, 2)}\n`;
}
