default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    # Process all consumer queues, including Solid Queue recurring tasks.
    - queues: "*"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
