name: Test, Scan and Analyze Frontend

permissions:
  contents: read

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  rubocop:
    name: Run RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Set up Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1
        with:
          bundler-cache: true
      - name: Install Dependencies
        run: bundle install
      - name: Run RuboCop
        run: bundle exec rubocop

  check-sonar-secret:
    name: Check SONAR TOKEN presence
    runs-on: ubuntu-latest
    outputs:
      has_sonar_token: ${{ steps.check_token.outputs.has_sonar_token }}
    steps:
      - name: Check SONAR_TOKEN presence
        id: check_token
        run: |
          if [[ -n "${SONAR_TOKEN}" ]]; then
            echo "has_sonar_token=true" >> "$GITHUB_OUTPUT"
          else
            echo "has_sonar_token=false" >> "$GITHUB_OUTPUT"
          fi
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  run-sonarcloud-analysis:
    name: Run SonarCloud Analysis
    needs: [check-sonar-secret, rubocop] # This ensures RuboCop runs before SonarCloud analysis
    runs-on: ubuntu-latest
    if: needs.check-sonar-secret.outputs.has_sonar_token == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@02ef91109b2d589e757aefcfb2854c2783fd7b19 # v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
